openapi: "3.0.0"
info:
  title: 情報管理システム
  version: 1.0.0
servers:
  - url: "http://localhost:8002"
tags:
  - name: sample
    description: サンプルだにょん
paths:
  /sample/{id}:
    get:
      description: サンプル説明
      tags:
        - sample
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int32
      responses:
        201:
          description: 正常系
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Sample"
        default:
          description: 異常系
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Other"
components:
  schemas:
    Sample:
      type: object
      required:
        - name
      properties:
        id:
          type: integer
          format: int32
          example: 100
        name:
          type: string
          example: anti-paper
        status:
          type: string
          description: 状態
          enum:
            - 有効
            - 非有効
    Other:
      type: object
      properties:
        status:
          type: boolean
          example: false
        message:
          type: string
          example: "Not found."
    NotFound:
      type: object
      properties:
        status:
          type: boolean
          example: false
        message:
          type: string
          example: コンテンツがありません。
    UnprocessableEntityAboutName:
      type: object
      properties:
        status:
          type: boolean
          example: false
        message:
          type: string
          example: "'name'は必須項目です。"
    UnprocessableEntityAboutIsDone:
      type: object
      properties:
        status:
          type: boolean
          example: false
        message:
          type: string
          example: "'is_done'は必須項目です。"
    UnprocessableEntityAboutTrashDay:
      type: object
      properties:
        status:
          type: boolean
          example: false
        message:
          type: string
          example: "'trash_day'は必須項目です。"
    InternalServerError:
      type: object
      properties:
        status:
          type: boolean
          example: false
        message:
          type: string
          example: 予期せぬエラーが発生しました。