openapi: "3.0.0"
info:
  title: 情報管理システム
  version: "1.0"
servers:
  - url: "http://localhost:8002"
tags:
  - name: top
    description: トップページで必要になる情報をまとめて管理
  - name: task
    description: タスク管理
  - name: schedule
    description: スケジュール管理
paths:
  /all:
    get:
      description: 本日以前が対象となる情報の概要を取得する
      tags:
        - top
      responses:
        200:
          description: 正常系
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TopInfo"
        500:
          description: 予期せぬエラー
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/InternalServerError"
  /task/register:
    post:
      description: タスクを新規に登録する
      tags:
        - task
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/LongTask"
      responses:
        200:
          description: 正常系
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TaskRegistered"
        422:
          description: バリデーションエラー
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TaskUnprocessable"
        500:
          description: 予期せぬエラー
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/InternalServerError"
  /task/{id}/info:
    get:
      description: タスクを取得する
      tags:
        - task
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int32
            example: 3
      responses:
        200:
          description: 正常系
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TaskInfo"
        404:
          description: タスクなし
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/NotFound"
        500:
          description: 予期せぬエラー
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/InternalServerError"
  /task/{id}/update:
    put:
      description: タスクを更新する
      tags:
        - task
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int32
            example: 3
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/LongTask"
      responses:
        200:
          description: 正常系
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TaskUpdated"
        404:
          description: タスクなし
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/NotFound"
        422:
          description: バリデーションエラー
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TaskUnprocessable"
        500:
          description: 予期せぬエラー
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/InternalServerError"
  /task/{id}/done:
    put:
      description: タスクを完了する
      tags:
        - task
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int32
            example: 3
      responses:
        200:
          description: 正常系
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TaskDone"
        404:
          description: タスクなし
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/NotFound"
        500:
          description: 予期せぬエラー
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/InternalServerError"
  /task/{id}/delete:
    delete:
      description: タスクを削除する
      tags:
        - task
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int32
            example: 3
      responses:
        200:
          description: 正常系
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TaskDeleted"
        404:
          description: タスクなし
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/NotFound"
        500:
          description: 予期せぬエラー
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/InternalServerError"
  /schedule/list:
    get:
      description: スケジュール一覧を取得する
      tags:
        - schedule
      responses:
        200:
          description: 正常系
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ScheduleList"
        500:
          description: 予期せぬエラー
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/InternalServerError"
  /schedule/register:
    post:
      description: スケジュールを新規に登録する
      tags:
        - schedule
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/LongSchedule"
      responses:
        200:
          description: 正常系
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ScheduleRegistered"
        422:
          description: バリデーションエラー
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ScheduleUnprocessable"
        500:
          description: 予期せぬエラー
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/InternalServerError"
  /schedule/{id}/info:
    get:
      description: スケジュールを取得する
      tags:
        - schedule
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int32
            example: 3
      responses:
        200:
          description: 正常系
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ScheduleInfo"
        404:
          description: スケジュールなし
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/NotFound"
        500:
          description: 予期せぬエラー
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/InternalServerError"
  /schedule/{id}/update:
    put:
      description: スケジュールを更新する
      tags:
        - schedule
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int32
            example: 3
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/LongSchedule"
      responses:
        200:
          description: 正常系
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ScheduleUpdated"
        404:
          description: スケジュールなし
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/NotFound"
        422:
          description: バリデーションエラー
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ScheduleUnprocessable"
        500:
          description: 予期せぬエラー
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/InternalServerError"
  /schedule/{id}/delete:
    delete:
      description: スケジュールを削除する
      tags:
        - schedule
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int32
            example: 3
      responses:
        200:
          description: 正常系
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ScheduleDeleted"
        404:
          description: スケジュールなし
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/NotFound"
        500:
          description: 予期せぬエラー
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/InternalServerError"
components:
  schemas:
    ShortTask:
      type: object
      properties:
        id:
          type: integer
          format: int32
        name:
          type: string
        target_date:
          type: string
    LongTask:
      type: object
      required:
        - name
        - target_date
      properties:
        name:
          type: string
          example: 読書
        content:
          type: string
          example: |-
            以下読む
            ・サルでもわかるAWS
            ・サルでもわかる要件定義
        target_date:
          type: string
          example: "2024/7/23"
    ShortSchedule:
      type: object
      properties:
        id:
          type: integer
          format: int32
        name:
          type: string
        start_datetime:
          type: string
        end_datetime:
          type: string
    LongSchedule:
      type: object
      required:
        - name
        - frequency
        - month
        - day
        - week_day
        - start_datetime
      properties:
        name:
          type: string
          example: バイオリンレッスン
        content:
          type: string
          example: "-"
        frequency:
          type: integer
          format: int32
          example: 0
        month:
          type: integer
          format: int32
          example: 1
        day:
          type: integer
          format: int32
          example: 1
        week_day:
          type: integer
          format: int32
          example: 0
        start_datetime:
          type: string
          example: "2021/3/16 15:00:00"
        end_datetime:
          type: string
          example: "2025/7/23 16:00:00"
    Shcedules:
      type: array
      items:
        $ref: "#/components/schemas/ShortSchedule"
      example:
        - id: 1
          name: バイオリンレッスン
          start_datetime: '2021-03-16 15:00:00'
          end_datetime: '2025-07-23 16:00:00'
        - id: 2
          name: 脱毛
          start_datetime: '2022-02-22 13:00:00'
          end_datetime: null
    ShortMuscleTrainingHistory:
      type: object
      properties:
        id:
          type: integer
          format: int32
        name:
          type: string
        count:
          type: integer
          format: int32
        created_at:
          type: string
    Top:
      type: object
      properties:
        tasks:
          type: array
          items:
            $ref: "#/components/schemas/ShortTask"
          example:
            - id: 1
              name: 読書
              target_date: '2025-03-21'
        schedules:
          type: array
          items:
            $ref: "#/components/schemas/ShortSchedule"
          example:
            - id: 1
              name: ゴミ捨て
              start_datetime: '2025-03-21 09:00:00'
              end_datetime: '2025-03-21 09:00:00'
            - id: 2
              name: バイオリンレッスン
              start_datetime: '2021-03-16 15:00:00'
              end_datetime: '2025-07-23 16:00:00'
        muscle_training_histories:
          type: array
          items:
            $ref: "#/components/schemas/ShortMuscleTrainingHistory"
          example:
            - id: 1
              name: ゴミ捨て
              count: 15
              created_at: '2025-03-21 03:44:25'
    TopInfo:
      type: object
      properties:
        status:
          type: boolean
          example: true
        data:
          $ref: "#/components/schemas/Top"
    TaskRegistered:
      type: object
      properties:
        status:
          type: boolean
          example: true
        message:
          type: string
          example: タスクの登録が完了しました。
    TaskInfo:
      type: object
      properties:
        status:
          type: boolean
          example: true
        data:
          $ref: "#/components/schemas/LongTask"
    TaskUpdated:
      type: object
      properties:
        status:
          type: boolean
          example: true
        message:
          type: string
          example: タスクの更新が完了しました。
    TaskDone:
      type: object
      properties:
        status:
          type: boolean
          example: true
        message:
          type: string
          example: タスクの完了処理が完了しました。
    TaskDeleted:
      type: object
      properties:
        status:
          type: boolean
          example: true
        message:
          type: string
          example: タスクの削除が完了しました。
    ScheduleList:
      type: object
      properties:
        status:
          type: boolean
          example: true
        data:
          type: array
          $ref: "#/components/schemas/Shcedules"
    ScheduleRegistered:
      type: object
      properties:
        status:
          type: boolean
          example: true
        message:
          type: string
          example: スケジュールの登録が完了しました。
    ScheduleInfo:
      type: object
      properties:
        status:
          type: boolean
          example: true
        data:
          $ref: "#/components/schemas/LongSchedule"
    ScheduleUpdated:
      type: object
      properties:
        status:
          type: boolean
          example: true
        message:
          type: string
          example: スケジュールの更新が完了しました。
    ScheduleDeleted:
      type: object
      properties:
        status:
          type: boolean
          example: true
        message:
          type: string
          example: スケジュールの削除が完了しました。
    NotFound:
      type: object
      properties:
        status:
          type: boolean
          example: false
        message:
          type: string
          example: コンテンツがありません。
    TaskUnprocessable:
      type: object
      properties:
        status:
          type: boolean
          example: false
        messages:
          type: array
          items:
            type: string
          example:
            - "'name'は必須項目です。"
            - "'target_date'は必須項目です。"
    ScheduleUnprocessable:
      type: object
      properties:
        status:
          type: boolean
          example: false
        messages:
          type: array
          items:
            type: string
          example:
            - "'name'は必須項目です。"
            - "'start_datetime'は必須項目です。"
    InternalServerError:
      type: object
      properties:
        status:
          type: boolean
          example: false
        message:
          type: string
          example: 予期せぬエラーが発生しました。
